//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College941.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudent
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
